config/routes.rb
Rails.application.routes.draw do
  root 'admin/products#index'

  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      post 'products' => 'products#create'
    end
  end

  namespace :admin do
    resources :products, only: [:edit, :update, :index]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :sku_id
  validates :sku_id, uniqueness: true
  # scope :category_search, ->(val) { where("'#{val}' = ANY (categories)") }
  # scope :tag_search, ->(val) { where("'#{val}' = ANY (tags)") }
  before_save :remove_blank_vales

  private
  def remove_blank_vales
    categories.delete_if(&:blank?)
    tags.delete_if(&:blank?)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(update_product_params)
      flash[:success] = 'Successfully Updated.'
      redirect_to admin_products_path
    else
      flash[:error] = @product.errors.full_messages.join('. ')
      render :edit
    end
  end

  private

  def update_product_params
    prod_params = params.require(:product).permit(:expire_date, :name,
                                                  { categories: [] },
                                                  { tags: [] },
                                                  :price,
                                                  :description,
                                                  :admin_approved)
    prod_params[:categories] = [] if prod_params[:categories].blank?
    prod_params[:tags] = [] if prod_params[:tags].blank?
    prod_params
  end
end

app/controllers/api/v1/products_controller.rb
module Api
  class V1::ProductsController < ApplicationController
    skip_before_filter  :verify_authenticity_token
    protect_from_forgery :except => [:create]

    def create
      product = Product.new(product_params)
      respond_to do |format|

        if product.save
          format.json { render json: {message: 'Successfully Created.'}, status: :created }
        else
          format.json { render json: { erorrs: product.errors }, status: :unprocessable_entity }
        end
      end
    end

    private

    def product_params
      params.require(:product).permit(:expire_date, :name, :sku_id,
                                      { categories: [] },
                                      { tags: [] },
                                      { images: [:img_path] },
                                      :price,
                                      :description)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def categories(categories)
    content_tag :ul do
      categories.each do |category|
        concat content_tag(:li, category)
      end
    end
  end

  def tags(tags)
    content_tag :ul do
      tags.each do |tag|
        concat content_tag(:li, tag)
      end
    end
  end

  def first_image(hash)
    hash.present? ? hash['0']['img_path'] : ''
  end

  def image_path(image)
    image['img_path']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/products/_category.html.haml
- @product.categories.each do |category|
  %div{style: 'margin-left: 20px;'}
    = hidden_field_tag('product[categories][]', category)
    = label_tag 'name', category
    = link_to "Remove", '#', onclick: 'remove(this)'

app/views/admin/products/_form.html.haml
:javascript
  $(function(){
    $('#add_tag').click(product.addTags);
    $('#add_category').click(product.addCategories);
    $("#product_form").submit(product.formValidate);
  });
  function remove(that){
    $(that).parent().remove();
    return event.preventDefault();
  };
  

%div
  %div{ style: 'width: 750px;margin-left: 28%;' }
    = form_for([:admin, @product], html: { id: 'product_form'}) do |f|
      .main-col1
        %div
          = f.label :name
          = f.text_field :name, :tabindex => "1",:autofocus =>"autofocus"
        %br
        %div
          = f.label :description
          = f.text_area :description, :tabindex => "2", :rows => 2, cols: 50, rows: 10
        %br
        = f.label :sku_id
        = f.label :sku_id, @product.sku_id, class: 'label'
        %br
        %br
        = f.label :price
        = f.number_field :price, :tabindex => "4", step: 0.01
        %br
        = f.label :admin_approved
        = f.check_box :admin_approved, {}, 'true', 'false'
      .main-col2
        = render 'images'
        %label
          %span Categories
          = render 'category'
          #categories
          = link_to "Add Category", '#', id: 'add_category'
        %br 
        %br
        %label
          %span Tag
          = render 'tag'
          #tags
          = link_to "Add Tag", '#', id: 'add_tag'
        %br
      .clear
        %div{ align: 'center'}
          = f.submit

app/views/admin/products/_images.html.haml
- @product.images.each do |key, image|
  = label_tag 'image', 'Image'
  = label_tag 'image', image_path(image), class: 'label'
  %br
  %br

app/views/admin/products/_tag.html.haml
- @product.tags.each do |tag|
  %div{style: 'margin-left: 20px;'}
    = hidden_field_tag('product[tags][]', tag)
    = label_tag 'name', tag
    = link_to "Remove", '#', onclick: 'remove(this)'

app/views/admin/products/edit.html.haml
= render 'form'

app/views/admin/products/index.html.haml
%table
  %thead
    %tr.blue
      %th{:width => "14%"} Name
      %th{:width => "14%"} Description
      %th{:width => "15%"} Sku_id
      %th{:width => "18%"} Price
      %th{:width => "15%"} Picture
      %th Categories
      %th Tags
      %th Admin Approved
  %tbody
    - @products.each do |product|
      %tr
        %th
          = link_to product.name, edit_admin_product_path(product)
        %th
          = product.description
        %th
          = link_to product.sku_id, edit_admin_product_path(product)
        %th
          = product.price
        %th
          = first_image(product.images)
        %th
          = categories(product.categories)
        %th
          = tags(product.tags)
        %th
          = product.admin_approved

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Assignment
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if flash[:success].present?
      = flash[:success]
    - if flash[:error].present?
      = flash[:error]
    = yield